import type { Locale } from '@/domain/models/locale';

/** Canonical site origin used for absolute URLs in SEO artifacts. */
export const SITE_ORIGIN = 'https://josunlp.de';

/** Owner identity (owner-provided data; see docs/OWNER_ACTION_REQUIRED.md). */
export const OWNER = {
	name: 'Jonas Pfalzgraf',
	alias: 'JosunLP',
	email: 'info@josunlp.de',
	supportEmail: 'support@josunlp.de',
	gitHubUrl: 'https://github.com/JosunLP',
	koFiUrl: 'https://ko-fi.com/josunlp',
} as const;

/**
 * Social preview card, generated by `scripts/generate-og-image.ts`.
 * Dimensions are declared to crawlers so they can lay out the card before
 * the image itself has been fetched.
 */
export const OG_IMAGE = {
	path: '/og-image.png',
	width: 1200,
	height: 630,
	type: 'image/png',
} as const;

/** Local-storage keys for strictly necessary user preferences. */
export const STORAGE_KEYS = {
	/** Explicitly chosen locale ('de' | 'en'), set only on user action. */
	locale: 'jp:locale',
	/** Explicitly chosen theme ('light' | 'dark'), set only on user action. */
	theme: 'jp:theme',
} as const;

/** Page identifiers used for navigation and route mapping. */
export const PAGE_IDS = [
	'home',
	'about',
	'projects',
	'blog',
	'contact',
	'imprint',
	'privacy',
	'accessibility',
] as const;

export type PageId = (typeof PAGE_IDS)[number];

/** Pages linked in the header navigation, in order. */
export const HEADER_NAV: readonly PageId[] = [
	'home',
	'projects',
	'blog',
	'about',
	'contact',
];

/** Pages linked in the footer legal navigation, in order. */
export const FOOTER_LEGAL_NAV: readonly PageId[] = [
	'imprint',
	'privacy',
	'accessibility',
];

/** Path segment per page and locale (localized, human-readable URLs). */
const PAGE_SEGMENTS: Readonly<Record<PageId, string>> = {
	home: '',
	about: 'about',
	projects: 'projects',
	blog: 'blog',
	contact: 'contact',
	imprint: 'imprint',
	privacy: 'privacy',
	accessibility: 'accessibility',
};

/** Returns the absolute path of a static page for a locale. */
export function pagePath(locale: Locale, page: PageId): string {
	const segment = PAGE_SEGMENTS[page];
	return segment === '' ? `/${locale}/` : `/${locale}/${segment}/`;
}

/** Returns the absolute path of a blog article for a locale. */
export function blogPostPath(locale: Locale, slug: string): string {
	return `/${locale}/blog/${slug}/`;
}
